/**
 * Metal execution tests — the Metal half of the two-dialect gate.
 *
 * These run a kernel generated by `internal:tensor/ir` on the actual GPU: emit
 * MSL, compile it through the Objective-C runtime, dispatch it, wait on an
 * `MTLSharedEvent` through the blocking pool, and read the result back from
 * unified memory. Every FFI assumption the Metal backend rests on is exercised
 * here — `objc_msgSend` signature binding, by-value `MTLSize` struct arguments,
 * `NSError **` out-parameters, async compilation, and zero-copy readback.
 *
 * Skipped when no Metal device is present.
 */
import { describe, it } from 'fino:test/test';
import {
  createMetalApi,
  metalAvailable,
  metalUnavailableReason,
  objcAvailable,
  nsString,
  readNSString,
} from 'internal:metal';
import {
  SMALL_TILING,
  binaryKernel,
  gemmGrid,
  gemmKernel,
  lowerToMSL,
  packParams,
  unaryKernel,
} from 'internal:tensor/ir';

/** Whether to run the GPU tests at all. */
const available = metalAvailable();

describe('Objective-C runtime', () => {
  it('loads, or explains why not', (t) => {
    if (!objcAvailable()) {
      t.ok(true, 'SKIP: no Objective-C runtime on this platform');
      return;
    }
    t.ok(true, 'the runtime loaded');
  });
  it('round-trips an NSString', (t) => {
    if (!objcAvailable()) {
      t.ok(true, 'SKIP: no Objective-C runtime on this platform');
      return;
    }
    // Proves selector registration, class lookup, and both message-send
    // signatures used for string handling.
    const text = 'hello from fino';
    t.equal(readNSString(nsString(text)), text, 'NSString round-trips');
  });
  it('handles non-ASCII text', (t) => {
    if (!objcAvailable()) {
      t.ok(true, 'SKIP: no Objective-C runtime on this platform');
      return;
    }
    // Byte length and character length differ here, which is exactly what
    // lengthOfBytesUsingEncoding: is for.
    const text = 'gradient ∇ café';
    t.equal(readNSString(nsString(text)), text, 'UTF-8 survives the round-trip');
  });
});

describe('Metal device', () => {
  it('reports device capabilities', (t) => {
    if (!available) {
      t.ok(true, `SKIP: ${metalUnavailableReason()}`);
      return;
    }
    const api = createMetalApi();
    const device = api.createDevice();
    const info = api.deviceInfo(device);
    t.ok(info.name.length > 0, `device is named (${info.name})`);
    t.ok(info.unifiedMemory, 'Apple Silicon reports unified memory');
    t.ok(
      info.maxThreadsPerThreadgroup >= 256,
      `threadgroups of at least 256 (${info.maxThreadsPerThreadgroup})`,
    );
    api.destroy(device);
  });
  it('allocates a buffer and shares it with the host', (t) => {
    if (!available) {
      t.ok(true, `SKIP: ${metalUnavailableReason()}`);
      return;
    }
    const api = createMetalApi();
    const device = api.createDevice();
    const buffer = api.createBuffer(device, 16);
    // Unified memory: this view aliases the device's own storage, so a host write
    // is immediately what the GPU will read.
    const view = new Float32Array(api.bufferContents(buffer, 16));
    view[0] = 1.5;
    view[3] = -2.5;
    const again = new Float32Array(api.bufferContents(buffer, 16));
    t.equal(again[0], 1.5, 'host writes are visible through a second view');
    t.equal(again[3], -2.5, 'and at the right offset');
    api.destroy(buffer);
    api.destroy(device);
  });
  it('reports a compilation error rather than crashing', async (t) => {
    if (!available) {
      t.ok(true, `SKIP: ${metalUnavailableReason()}`);
      return;
    }
    const api = createMetalApi();
    const device = api.createDevice();
    await t.rejects(
      () => api.compileLibrary(device, 'this is not valid MSL'),
      /compilation failed/,
      'the NSError out-parameter is read back as a message',
    );
    api.destroy(device);
  });
});

describe('Metal kernel execution', () => {
  it('runs an IR-generated elementwise add on the GPU', async (t) => {
    if (!available) {
      t.ok(true, `SKIP: ${metalUnavailableReason()}`);
      return;
    }
    const api = createMetalApi();
    const device = api.createDevice();
    const queue = api.createQueue(device);
    const event = api.createSharedEvent(device);

    // The same template the tensor engine uses, lowered to MSL.
    const { ir } = binaryKernel(
      'add',
      [
        { dtype: 'f32', layout: 'cont' },
        { dtype: 'f32', layout: 'cont' },
      ],
      'f32',
    );
    const source = lowerToMSL(ir, { fastMath: false });
    const library = await api.compileLibrary(device, source);
    const pipeline = api.createPipeline(device, library, ir.name);
    t.ok(
      pipeline.maxThreadsPerThreadgroup >= ir.wg[0],
      `the pipeline supports the kernel's workgroup (${pipeline.maxThreadsPerThreadgroup} >= ${ir.wg[0]})`,
    );
    t.ok(
      pipeline.threadExecutionWidth >= 8,
      `the pipeline reports its SIMD width (${pipeline.threadExecutionWidth})`,
    );

    const count = 1024;
    const bytes = count * 4;
    const a = api.createBuffer(device, bytes);
    const b = api.createBuffer(device, bytes);
    const out = api.createBuffer(device, bytes);
    const aView = new Float32Array(api.bufferContents(a, bytes));
    const bView = new Float32Array(api.bufferContents(b, bytes));
    for (let i = 0; i < count; i++) {
      aView[i] = i;
      bView[i] = i * 2;
    }

    const params = packParams(ir.params, { n: count });
    const threadgroups = Math.ceil(count / ir.wg[0]);
    const batch = api.beginBatch(queue);
    api.encode(batch, {
      pipeline,
      buffers: [
        { buffer: a, offset: 0 },
        { buffer: b, offset: 0 },
        { buffer: out, offset: 0 },
      ],
      params,
      grid: [threadgroups, 1, 1],
      threadgroup: ir.wg,
    });
    api.commitBatch(batch, event, 1n);

    const finished = await api.waitForEvent(event, 1n, 5000);
    t.ok(finished, 'the shared event signalled before the timeout');
    t.equal(api.eventValue(event), 1n, 'and reached the expected value');

    const result = new Float32Array(api.bufferContents(out, bytes));
    let mismatches = 0;
    for (let i = 0; i < count; i++) {
      if (result[i] !== i * 3) mismatches++;
    }
    t.equal(mismatches, 0, 'every element equals a + b');

    api.destroy(out);
    api.destroy(b);
    api.destroy(a);
    api.destroy(pipeline.state);
    api.destroy(library);
    api.destroy(event);
    api.destroy(queue);
    api.destroy(device);
  });
  it('runs an IR-generated tiled GEMM on the GPU', async (t) => {
    if (!available) {
      t.ok(true, `SKIP: ${metalUnavailableReason()}`);
      return;
    }
    // GEMM is the honesty test: shared memory, barriers, a real loop nest, and
    // mutable register accumulators, all from the same dialect-neutral IR.
    const api = createMetalApi();
    const device = api.createDevice();
    const queue = api.createQueue(device);
    const event = api.createSharedEvent(device);

    const tiling = SMALL_TILING;
    const { ir } = gemmKernel({ dtype: 'f32', tiling });
    const library = await api.compileLibrary(device, lowerToMSL(ir, { fastMath: false }));
    const pipeline = api.createPipeline(device, library, ir.name);

    // A ragged size on purpose, so the edge guards are exercised.
    const m = 65;
    const k = 33;
    const n = 47;
    const aBytes = m * k * 4;
    const bBytes = k * n * 4;
    const cBytes = m * n * 4;
    const a = api.createBuffer(device, aBytes);
    const b = api.createBuffer(device, bBytes);
    const c = api.createBuffer(device, cBytes);
    const aView = new Float32Array(api.bufferContents(a, aBytes));
    const bView = new Float32Array(api.bufferContents(b, bBytes));
    for (let i = 0; i < m * k; i++) aView[i] = ((i % 7) - 3) / 4;
    for (let i = 0; i < k * n; i++) bView[i] = ((i % 5) - 2) / 3;

    const params = packParams(ir.params, { M: m, N: n, K: k });
    const batch = api.beginBatch(queue);
    api.encode(batch, {
      pipeline,
      buffers: [
        { buffer: a, offset: 0 },
        { buffer: b, offset: 0 },
        { buffer: c, offset: 0 },
      ],
      params,
      grid: gemmGrid(m, n, tiling),
      threadgroup: ir.wg,
    });
    api.commitBatch(batch, event, 1n);
    t.ok(await api.waitForEvent(event, 1n, 10000), 'the GEMM completed');

    // Compare against a straightforward host implementation.
    const result = new Float32Array(api.bufferContents(c, cBytes));
    let worst = 0;
    for (let row = 0; row < m; row++) {
      for (let col = 0; col < n; col++) {
        let expected = 0;
        for (let i = 0; i < k; i++) expected += aView[row * k + i]! * bView[i * n + col]!;
        worst = Math.max(worst, Math.abs(result[row * n + col]! - expected));
      }
    }
    t.ok(worst < 1e-4, `GPU GEMM matches the host to ${worst}`);

    api.destroy(c);
    api.destroy(b);
    api.destroy(a);
    api.destroy(pipeline.state);
    api.destroy(library);
    api.destroy(event);
    api.destroy(queue);
    api.destroy(device);
  });
  it('keeps the event loop responsive while the GPU works', async (t) => {
    if (!available) {
      t.ok(true, `SKIP: ${metalUnavailableReason()}`);
      return;
    }
    // The whole point of parking the fence wait on the blocking pool: a timer
    // must still fire while the GPU is busy.
    const api = createMetalApi();
    const device = api.createDevice();
    const queue = api.createQueue(device);
    const event = api.createSharedEvent(device);
    const { ir } = unaryKernel('relu', { dtype: 'f32', layout: 'cont' }, 'f32');
    const library = await api.compileLibrary(device, lowerToMSL(ir));
    const pipeline = api.createPipeline(device, library, ir.name);

    const count = 1 << 20;
    const bytes = count * 4;
    const input = api.createBuffer(device, bytes);
    const out = api.createBuffer(device, bytes);
    const inputView = new Float32Array(api.bufferContents(input, bytes));
    for (let i = 0; i < count; i++) inputView[i] = i % 2 === 0 ? -1 : 2;

    const batch = api.beginBatch(queue);
    api.encode(batch, {
      pipeline,
      buffers: [
        { buffer: input, offset: 0 },
        { buffer: out, offset: 0 },
      ],
      params: packParams(ir.params, { n: count }),
      grid: [Math.ceil(count / ir.wg[0]), 1, 1],
      threadgroup: ir.wg,
    });
    api.commitBatch(batch, event, 1n);

    let timerFired = false;
    const timer = new Promise<void>((resolve) => {
      setTimeout(() => {
        timerFired = true;
        resolve();
      }, 0);
    });
    const waited = api.waitForEvent(event, 1n, 5000);
    await Promise.all([timer, waited]);
    t.ok(timerFired, 'a timer fired while the fence wait was outstanding');
    t.ok(await waited, 'and the fence still signalled');

    const result = new Float32Array(api.bufferContents(out, bytes));
    t.equal(result[0], 0, 'relu clamped the negative input');
    t.equal(result[1], 2, 'and passed the positive one through');

    api.destroy(out);
    api.destroy(input);
    api.destroy(pipeline.state);
    api.destroy(library);
    api.destroy(event);
    api.destroy(queue);
    api.destroy(device);
  });
});
