[package]
name = "fino"
version = "0.1.0"
edition = "2024"

[dependencies]
cherenkov = { path = "../cherenkov" }
v8 = "139.0.0"
libc = "0.2"
libffi = "5.1.0"
libloading = "0.8"
smallvec = "1.13"
oxc_allocator = { version = "0.123", features = ["serialize"] }
oxc_ast = { version = "0.123", features = ["serialize"] }
oxc_codegen = "0.123"
oxc_data_structures = "0.123"
oxc_parser = "0.123"
oxc_semantic = "0.123"
oxc_sourcemap = "6.1.1"
oxc_span = { version = "0.123", features = ["serialize"] }
oxc_transformer = "0.123"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-executor = "1"
futures-channel = "0.3"
blocking = "1"

[build-dependencies]
cc = "1"
oxc_allocator = "0.123"
oxc_codegen = "0.123"
oxc_parser = "0.123"
oxc_semantic = "0.123"
oxc_sourcemap = "6.1.1"
oxc_span = "0.123"
oxc_transformer = "0.123"
