/**
* Golden interop tests for internal:format/thrift against bytes produced by the
* reference Apache Thrift Python library. Fixtures are generated by
* tests/fixtures/thrift/generate_fixtures.py where the `thrift` package is
* available and committed; these tests skip with a notice when absent.
*/
import { describe, it } from 'fino:test/test';
import { BinaryProtocol, CompactProtocol, TType, readStruct, type Protocol } from 'internal:format/thrift';
import { DiskFileSystem } from 'fino:file';
const fs = new DiskFileSystem();
const DIR = 'tests/fixtures/thrift';
async function readFixture(name: string): Promise<Uint8Array | null> {
  try {
    const file = await fs.open(`${DIR}/${name}`, 'r');
    const bytes = await file.bytes();
    await file.close();
    return bytes;
  } catch {
    return null;
  }
}
function assertGolden(t: {
  deepEqual(a: unknown, b: unknown, m?: string): void;
  equal(a: unknown, b: unknown, m?: string): void;
}, proto: Protocol): void {
  const fields = readStruct(proto);
  t.deepEqual(fields.get(1), {
    type: TType.I32,
    value: 42
  }, 'field 1 i32=42');
  t.deepEqual(fields.get(2), {
    type: TType.STRING,
    value: 'héllo'
  }, 'field 2 string');
  t.deepEqual(fields.get(3), {
    type: TType.LIST,
    elemType: TType.I32,
    values: [
      {
        type: TType.I32,
        value: 1
      },
      {
        type: TType.I32,
        value: 2
      },
      {
        type: TType.I32,
        value: 3
      }
    ]
  }, 'field 3 list<i32>');
  t.deepEqual(fields.get(4), {
    type: TType.BOOL,
    value: true
  }, 'field 4 bool');
  t.deepEqual(fields.get(5), {
    type: TType.I64,
    value: 1n << 40n
  }, 'field 5 i64');
}
describe('thrift reference-library golden interop', () => {
  it('reads a compact struct produced by Apache Thrift, or skips', async (t) => {
    const bytes = await readFixture('golden.compact');
    if (bytes === null) {
      t.ok(true, 'SKIP: run tests/fixtures/thrift/generate_fixtures.py with the thrift package to enable');
      return;
    }
    assertGolden(t, new CompactProtocol(bytes));
  });
  it('reads a binary struct produced by Apache Thrift, or skips', async (t) => {
    const bytes = await readFixture('golden.binary');
    if (bytes === null) {
      t.ok(true, 'SKIP: fixtures not generated');
      return;
    }
    assertGolden(t, new BinaryProtocol(bytes));
  });
});
