/**
 * internal:store/facade — generic Realm transport for `fino:store`.
 *
 * Store providers remain in the Realm that owns their resources. This module
 * exposes the base `Store` contract through a capability-scoped `Facade` and
 * reconstructs an ordinary `Store` in the consuming Realm. Namespace paths
 * cross the boundary explicitly rather than being folded into keys, so remote
 * and local stores preserve the same key and namespace semantics.
 *
 * Optional provider capabilities are intentionally narrowed away. Atomic
 * commits and native expiration need transport-specific contracts before they
 * can be shared safely; callers that require them must stay with the owning
 * provider or use a stronger adapter.
 *
 * @internal
 */
import { Facade } from '../../realm/index.ts';
import type { Store, StoreEntry, StoreListOptions } from '../../store.ts';

/** Scalar module shape generated by `createStoreFacade()`. @internal */
export interface StoreFacadeModule {
  /** Read `key` from the namespace `path`. */
  get(path: string[], key: string): Promise<unknown | null>;
  /** Store `value` under `key` in the namespace `path`. */
  set(path: string[], key: string, value: unknown): Promise<void>;
  /** List entries matching `options` in the namespace `path`. */
  list(path: string[], options?: StoreListOptions): Promise<StoreEntry[]>;
  /** Delete `key` from the namespace `path`. */
  remove(path: string[], key: string): Promise<boolean>;
}

type StoreSource = Store | (() => Store);

function sourceStore(source: StoreSource): Store {
  return typeof source === 'function' ? source() : source;
}

function scopedStore(source: StoreSource, path: unknown): Store {
  if (!Array.isArray(path) || path.some((name) => typeof name !== 'string')) {
    throw new TypeError('remote store namespace path must be an array of strings');
  }
  let store = sourceStore(source);
  for (const name of path) store = store.namespace(name);
  return store;
}

function storeKey(key: unknown): string {
  if (typeof key !== 'string') throw new TypeError('remote store key must be a string');
  return key;
}

/**
 * Expose the base `Store` operations as a synthetic Realm module.
 *
 * `source` may be a store or a resolver for a store whose owner is initialized
 * lazily. The resolver runs for each operation, while the returned facade owns
 * no provider lifecycle.
 *
 * @internal
 */
export function createStoreFacade(specifier: string, source: StoreSource): Facade {
  return new Facade(specifier, [])
    .handle('get', (path, key) => scopedStore(source, path).get(storeKey(key)))
    .handle('set', (path, key, value) => scopedStore(source, path).set(storeKey(key), value))
    .handle('list', (path, options) =>
      scopedStore(source, path).list((options ?? {}) as StoreListOptions),
    )
    .handle('remove', (path, key) => scopedStore(source, path).delete(storeKey(key)));
}

/**
 * Adapt a store facade module back to the base `Store` contract.
 *
 * Namespace views share the same remote provider and append to an immutable
 * namespace path. The adapter does not claim `atomic` or `expiration` support.
 *
 * @internal
 */
export function storeFromFacade(remote: StoreFacadeModule, path: string[] = []): Store {
  const namespacePath = [...path];
  return {
    async get<T = unknown>(key: string): Promise<T | null> {
      return (await remote.get(namespacePath, key)) as T | null;
    },
    set: (key, value) => remote.set(namespacePath, key, value),
    async list<T = unknown>(options: StoreListOptions = {}): Promise<StoreEntry<T>[]> {
      return (await remote.list(namespacePath, options)) as StoreEntry<T>[];
    },
    delete: (key) => remote.remove(namespacePath, key),
    namespace(name: string): Store {
      if (name.length === 0) throw new TypeError('Store namespace must not be empty');
      return storeFromFacade(remote, [...namespacePath, name]);
    },
  };
}
