/**
* Golden-file interop tests for fino:data/arrow against pyarrow-produced Arrow
* IPC files. The fixtures are generated by tests/fixtures/arrow/generate_fixtures.py
* on a machine with pyarrow and committed; when they are absent (pyarrow not yet
* run) these tests skip with a notice rather than fail.
*/
import { describe, it } from 'fino:test/test';
import * as arrow from 'fino:data/arrow';
import { DiskFileSystem } from 'fino:file';
import { env } from 'fino:process';
const fs = new DiskFileSystem();
const DIR = 'tests/fixtures/arrow';
async function readFixture(name: string): Promise<Uint8Array | null> {
  try {
    const file = await fs.open(`${DIR}/${name}`, 'r');
    const bytes = await file.bytes();
    await file.close();
    return bytes;
  } catch {
    return null;
  }
}
describe('arrow pyarrow golden interop', () => {
  it('reads pyarrow primitives (stream + file), or skips', async (t) => {
    const stream = await readFixture('primitives.arrows');
    if (stream === null) {
      t.ok(true, 'SKIP: run tests/fixtures/arrow/generate_fixtures.py with pyarrow to enable');
      return;
    }
    const table = arrow.tableFromIPC(stream);
    t.deepEqual(table.getChild('i8')!.toArray(), [
      1,
      -2,
      3,
      null
    ], 'i8 column matches pyarrow');
    t.deepEqual(table.getChild('i64')!.toArray(), [
      1n,
      2n,
      9007199254740993n,
      null
    ], 'i64 column matches pyarrow');
    t.deepEqual(table.getChild('b')!.toArray(), [
      true,
      false,
      true,
      null
    ], 'bool column matches pyarrow');
    const fileBytes = await readFixture('primitives.arrow');
    if (fileBytes !== null) {
      const fileTable = arrow.RecordBatchFileReader.from(fileBytes).toTable();
      t.deepEqual(fileTable.getChild('i32')!.toArray(), [
        1,
        2,
        3,
        4
      ], 'file format i32 matches');
    }
  });
  it('reads pyarrow strings, or skips', async (t) => {
    const bytes = await readFixture('strings.arrows');
    if (bytes === null) {
      t.ok(true, 'SKIP: fixtures not generated');
      return;
    }
    const table = arrow.tableFromIPC(bytes);
    t.deepEqual(table.getChild('s')!.toArray(), [
      'alpha',
      '',
      'grüße',
      null
    ], 'utf8 matches pyarrow');
  });
  it('reads pyarrow nested + dictionary, or skips', async (t) => {
    const nested = await readFixture('nested.arrows');
    if (nested === null) {
      t.ok(true, 'SKIP: fixtures not generated');
      return;
    }
    const table = arrow.tableFromIPC(nested);
    t.deepEqual(table.getChild('list')!.toArray(), [
      [1, 2],
      [],
      [
        3,
        4,
        5
      ],
      null
    ], 'list matches pyarrow');
    const dict = await readFixture('dictionary.arrows');
    if (dict !== null) {
      const dictTable = arrow.tableFromIPC(dict);
      t.deepEqual(dictTable.getChild('color')!.toArray(), [
        'red',
        'green',
        'red',
        'blue'
      ], 'dictionary matches pyarrow');
    }
  });
  it('writes a file pyarrow can read back (emits when requested)', async (t) => {
    if (env['FINO_WRITE_ARROW_GOLDEN'] !== '1') {
      t.ok(true, 'set FINO_WRITE_ARROW_GOLDEN=1 to emit tests/fixtures/arrow/fino_roundtrip.arrows');
      return;
    }
    const batch = arrow.RecordBatch.from({
      id: [
        1,
        2,
        3
      ],
      name: [
        'a',
        'b',
        'c'
      ]
    });
    const bytes = arrow.tableToIPC(batch);
    const file = await fs.open(`${DIR}/fino_roundtrip.arrows`, 'w');
    await file.write(bytes);
    await file.close();
    t.ok(true, 'wrote fino_roundtrip.arrows for pyarrow validation');
  });
});
