/**
 * Golden interop tests for fino:data/parquet against files written by pyarrow.
 * Fixtures are generated by tests/fixtures/parquet/generate_fixtures.py and
 * committed. Missing fixtures are a test failure: this suite is the release
 * gate that keeps Fino compatible with independent Parquet writers.
 *
 * PyArrow covers the broad logical-type and encoding surface; DuckDB provides
 * a second independent writer for the common analytics interchange path.
 */
import { describe, it } from 'fino:test/test';
import { ParquetError, readParquet } from 'fino:data/parquet';
import { DiskFileSystem } from 'fino:file';
import { readFileMetaData } from 'internal:data/parquet/metadata';
const fs = new DiskFileSystem();
const DIR = 'tests/fixtures/parquet';
async function readFixture(name: string): Promise<Uint8Array> {
  const file = await fs.open(`${DIR}/${name}`, 'r');
  const bytes = await file.bytes();
  await file.close();
  return bytes;
}
function readFooter(bytes: Uint8Array) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const footerLength = view.getUint32(bytes.byteLength - 8, true);
  return readFileMetaData(
    bytes.subarray(bytes.byteLength - 8 - footerLength, bytes.byteLength - 8),
  );
}
function readInt32(bytes: Uint8Array): number {
  return new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).getInt32(0, true);
}
describe('parquet pyarrow golden interop', () => {
  it('reads pyarrow primitives with dictionary and Snappy encoding', async (t) => {
    const bytes = await readFixture('primitives.parquet');
    const table = readParquet(bytes);
    t.deepEqual(table.getChild('i32')!.toArray(), [1, 2, 3, null], 'i32 matches pyarrow');
    t.deepEqual(
      table.getChild('i64')!.toArray(),
      [1n, 2n, 9007199254740993n, null],
      'i64 matches pyarrow',
    );
    t.deepEqual(table.getChild('b')!.toArray(), [true, false, true, null], 'bool matches pyarrow');
    t.deepEqual(
      table.getChild('s')!.toArray(),
      ['alpha', 'grüße', '', null],
      'string matches pyarrow',
    );
  });
  it('reads a pyarrow dictionary column', async (t) => {
    const bytes = await readFixture('dictionary.parquet');
    const table = readParquet(bytes);
    t.equal(table.numRows, 100, 'row count');
    t.deepEqual(table.getChild('color')!.get(0), 'red', 'first dictionary value');
    t.deepEqual(table.getChild('color')!.get(3), 'blue', 'fourth dictionary value');
  });
  it('reads pyarrow uncompressed and gzip files', async (t) => {
    const unc = await readFixture('uncompressed.parquet');
    t.equal(readParquet(unc).getChild('x')!.get(50), 50, 'uncompressed value');
    const gz = await readFixture('gzip.parquet');
    t.equal(readParquet(gz).getChild('x')!.get(99), 99, 'gzip value');
  });
  it('reads a pyarrow nested file with lists and structs', async (t) => {
    const bytes = await readFixture('nested.parquet');
    const table = readParquet(bytes);
    t.deepEqual(
      table.getChild('tags')!.toArray(),
      [['a', 'b'], [], ['c'], null],
      'list column matches pyarrow',
    );
    t.deepEqual(
      table.getChild('point')!.toArray(),
      [
        {
          x: 1,
          y: 2,
        },
        {
          x: 3,
          y: 4,
        },
        null,
        {
          x: 5,
          y: 6,
        },
      ],
      'struct column matches pyarrow',
    );
  });
  it('reads pyarrow logical types', async (t) => {
    const table = readParquet(await readFixture('logical-types.parquet'));
    t.deepEqual(table.getChild('decimal')!.toArray(), [12345n, -67890n, null], 'decimal');
    t.deepEqual(table.getChild('date')!.toArray(), [0, 1, null], 'date32');
    t.deepEqual(table.getChild('time')!.toArray(), [0, 1500, null], 'time32');
    t.deepEqual(table.getChild('timestamp')!.toArray(), [0n, 1000000n, null], 'timestamp');
    t.deepEqual(table.getChild('uint32')!.toArray(), [0, 4000000000, null], 'uint32');
  });
  it('reads pyarrow delta and byte-stream-split encodings', async (t) => {
    const delta = readParquet(await readFixture('delta.parquet'));
    t.deepEqual(
      delta.getChild('value')!.toArray(),
      Array.from({ length: 300 }, (_, i) => i * 7 - 500),
      'DELTA_BINARY_PACKED',
    );
    const split = readParquet(await readFixture('byte-stream-split.parquet'));
    t.deepEqual(
      split.getChild('value')!.toArray(),
      Array.from({ length: 128 }, (_, i) => i * 1.25),
      'BYTE_STREAM_SPLIT',
    );
  });
  it('preserves pyarrow row-group boundaries', async (t) => {
    const bytes = await readFixture('row-groups.parquet');
    const table = readParquet(bytes);
    t.equal(table.batches.length, 3, 'one record batch per row group');
    t.deepEqual(
      table.getChild('value')!.toArray(),
      Array.from({ length: 10 }, (_, i) => i),
      'all row groups are read in order',
    );
    const meta = readFooter(bytes);
    t.deepEqual(
      meta.rowGroups.map((group) => {
        const stats = group.columns[0]!.metaData!.statistics!;
        return {
          rows: group.numRows,
          min: readInt32(stats.minValue!),
          max: readInt32(stats.maxValue!),
          nulls: stats.nullCount,
        };
      }),
      [
        { rows: 4n, min: 0, max: 3, nulls: 0n },
        { rows: 4n, min: 4, max: 7, nulls: 0n },
        { rows: 2n, min: 8, max: 9, nulls: 0n },
      ],
      'row-group statistics',
    );
  });
});
describe('parquet multi-writer golden interop', () => {
  it('reads a DuckDB-authored analytics table', async (t) => {
    const table = readParquet(await readFixture('duckdb.parquet'));
    t.deepEqual(
      table.toArray(),
      [
        { id: 1, label: 'alpha', score: 1.5 },
        { id: 2, label: 'beta', score: 2.25 },
        { id: 3, label: null, score: null },
      ],
      'DuckDB rows',
    );
  });
});
describe('parquet external corruption handling', () => {
  it('rejects a truncated external file', async (t) => {
    const bytes = await readFixture('primitives.parquet');
    t.throws(() => readParquet(bytes.subarray(0, bytes.byteLength - 7)), ParquetError, 'truncated');
  });
  it('rejects an external file with a corrupt footer length', async (t) => {
    const bytes = (await readFixture('primitives.parquet')).slice();
    bytes[bytes.byteLength - 8] = 255;
    bytes[bytes.byteLength - 7] = 255;
    bytes[bytes.byteLength - 6] = 255;
    bytes[bytes.byteLength - 5] = 127;
    t.throws(() => readParquet(bytes), ParquetError, 'footer length');
  });
});
