/**
 * Golden interop tests for fino:data/parquet against files written by pyarrow.
 * Fixtures are generated by tests/fixtures/parquet/generate_fixtures.py where
 * pyarrow is available and committed; these tests skip when absent.
 *
 * pyarrow defaults to dictionary-encoded, Snappy-compressed pages, so these
 * exercise the reader's real-file decode paths.
 */
import { describe, it } from 'fino:test/test';
import { readParquet } from 'fino:data/parquet';
import { DiskFileSystem } from 'fino:file';
const fs = new DiskFileSystem();
const DIR = 'tests/fixtures/parquet';
async function readFixture(name: string): Promise<Uint8Array | null> {
  try {
    const file = await fs.open(`${DIR}/${name}`, 'r');
    const bytes = await file.bytes();
    await file.close();
    return bytes;
  } catch {
    return null;
  }
}
describe('parquet pyarrow golden interop', () => {
  it('reads pyarrow primitives (dictionary + snappy), or skips', async (t) => {
    const bytes = await readFixture('primitives.parquet');
    if (bytes === null) {
      t.ok(true, 'SKIP: run tests/fixtures/parquet/generate_fixtures.py with pyarrow to enable');
      return;
    }
    const table = readParquet(bytes);
    t.deepEqual(table.getChild('i32')!.toArray(), [1, 2, 3, null], 'i32 matches pyarrow');
    t.deepEqual(
      table.getChild('i64')!.toArray(),
      [1n, 2n, 9007199254740993n, null],
      'i64 matches pyarrow',
    );
    t.deepEqual(table.getChild('b')!.toArray(), [true, false, true, null], 'bool matches pyarrow');
    t.deepEqual(
      table.getChild('s')!.toArray(),
      ['alpha', 'grüße', '', null],
      'string matches pyarrow',
    );
  });
  it('reads a pyarrow dictionary column, or skips', async (t) => {
    const bytes = await readFixture('dictionary.parquet');
    if (bytes === null) {
      t.ok(true, 'SKIP: fixtures not generated');
      return;
    }
    const table = readParquet(bytes);
    t.equal(table.numRows, 100, 'row count');
    t.deepEqual(table.getChild('color')!.get(0), 'red', 'first dictionary value');
    t.deepEqual(table.getChild('color')!.get(3), 'blue', 'fourth dictionary value');
  });
  it('reads pyarrow uncompressed + gzip, or skips', async (t) => {
    const unc = await readFixture('uncompressed.parquet');
    if (unc === null) {
      t.ok(true, 'SKIP: fixtures not generated');
      return;
    }
    t.equal(readParquet(unc).getChild('x')!.get(50), 50, 'uncompressed value');
    const gz = await readFixture('gzip.parquet');
    if (gz !== null) t.equal(readParquet(gz).getChild('x')!.get(99), 99, 'gzip value');
  });
  it('reads a pyarrow nested file (list + struct), or skips', async (t) => {
    const bytes = await readFixture('nested.parquet');
    if (bytes === null) {
      t.ok(true, 'SKIP: fixtures not generated');
      return;
    }
    const table = readParquet(bytes);
    t.deepEqual(
      table.getChild('tags')!.toArray(),
      [['a', 'b'], [], ['c'], null],
      'list column matches pyarrow',
    );
    t.deepEqual(
      table.getChild('point')!.toArray(),
      [
        {
          x: 1,
          y: 2,
        },
        {
          x: 3,
          y: 4,
        },
        null,
        {
          x: 5,
          y: 6,
        },
      ],
      'struct column matches pyarrow',
    );
  });
});
